# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2024-08-02 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jellyroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='links',
            field=models.ManyToManyField(blank=True, to='jellyroll.ContentLink'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='comment_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
