# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2024-08-02 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jellyroll', '0002_auto_20240802_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='img/jellyroll/bookmarks/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='coderepository',
            name='public_changeset_template',
            field=models.URLField(blank=True, help_text="Template for viewing a changeset publically. Use '%s' for the revision number"),
        ),
        migrations.AlterField(
            model_name='coderepository',
            name='type',
            field=models.CharField(choices=[('svn', 'Subversion'), ('git', 'Git')], max_length=10),
        ),
        migrations.AlterField(
            model_name='coderepository',
            name='username',
            field=models.CharField(help_text='Your username/email for this SCM.', max_length=100),
        ),
        migrations.AlterField(
            model_name='photo',
            name='cc_license',
            field=models.URLField(blank=True, choices=[('http://creativecommons.org/licenses/by/2.0/', 'CC Attribution'), ('http://creativecommons.org/licenses/by-nd/2.0/', 'CC Attribution-NoDerivs'), ('http://creativecommons.org/licenses/by-nc-nd/2.0/', 'CC Attribution-NonCommercial-NoDerivs'), ('http://creativecommons.org/licenses/by-nc/2.0/', 'CC Attribution-NonCommercial'), ('http://creativecommons.org/licenses/by-nc-sa/2.0/', 'CC Attribution-NonCommercial-ShareAlike'), ('http://creativecommons.org/licenses/by-sa/2.0/', 'CC Attribution-ShareAlike')]),
        ),
        migrations.AlterField(
            model_name='photo',
            name='local_image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/flickr/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='artist_mbid',
            field=models.CharField(blank=True, max_length=36, verbose_name='MusicBrainz Artist ID'),
        ),
        migrations.AlterField(
            model_name='track',
            name='track_mbid',
            field=models.CharField(blank=True, max_length=36, verbose_name='MusicBrainz Track ID'),
        ),
    ]
